name: Build Pearl Bailey High School Front End

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 18
      - name: NPM Clean Install
        run: npm ci
      - name: NPM Run Test
        run: npm run test
      - name: NPM Run Build
        run: npm run build
